### ISSUE TITLE
configUrl cache issue when using Swagger-UI

### ISSUE THREAD

**Issue by abenjell** [springdoc/springdoc-openapi#1712]
**Describe the bug**
Hello, 
Our users access swagger using direct access to api : http://localhost:8080/api/v0/swagger-ui/index.html
And other users access the swagger UI behind nginx proxy : http://localhost/api/v0/myservice/swagger-ui/index.html
The problem is the config url is calculated just the first time and used for both access.
The issue is well known and described [here]( https://github.com/springdoc/springdoc-openapi/issues/331) 

**To Reproduce**
Call swagger ui using nginx proxy : http://localhost/api/v0/myservice/swagger-ui/index.html
Call swagger UI without the proxy : http://localhost:8080/api/v0/swagger-ui/index.html
In the second call we have error message : Failed to load remote configuration.
It's because it makes a call to http://localhost:8080/api/v0/myservice/v3/api-docs/swagger-config that is built the first time when calling the swagger via nginx.

- What version of spring-boot you are using?
   2.6.6
- What modules and versions of springdoc-openapi are you using?
   1.6.9
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem
   Please find [HelloController](https://github.com/abenjell/springDoc) with [nginxConfig](https://github.com/abenjell/springDoc/blob/main/nginx_local.conf)
**Expected behavior**
   Both URLS work without any impact:
   URL without nginx : http://localhost:8080/api/v0/swagger-ui/index.html
   URL with nginx      : http://localhost/api/v0/myservice/swagger-ui/index.html

**Screenshots**
![image](https://user-images.githubusercontent.com/33379974/174305827-f8775b3c-0aae-456d-b3ce-196408f641dc.png)
![image](https://user-images.githubusercontent.com/33379974/174306110-9dc78c65-37a7-4795-9b77-bce71310d4c3.png)

**Additional context**

Thank you for your help
Best Regards,

**Comment by rhu25** [comment]
how this is been solved, i am facing same issue

my api 
can visit swagger via https://localhost:8081/swagger-ui/index.html

but on my production which is a ui visit swagger via a proxy https://localhost:8082/services/swagger-ui/index.html

how do i handle make both works

**Comment by antechrestos** [comment]
@abenjell I referenced your issue from [mine](https://github.com/springdoc/springdoc-openapi/issues/1748)

**Comment by antechrestos** [comment]
@abenjell 

I made a hack on my side to fix the issue (does not work when two requests from different context path arrives at the same time

```java

public class AlwaysComputeConfigUrlSwaggerTransformer extends SwaggerIndexPageTransformer {

    public AlwaysComputeConfigUrlSwaggerTransformer(SwaggerUiConfigProperties swaggerUiConfig, SwaggerUiOAuthProperties swaggerUiOAuthProperties, SwaggerUiConfigParameters swaggerUiConfigParameters, SwaggerWelcomeCommon swaggerWelcomeCommon, ObjectMapperProvider objectMapperProvider) {
        super(swaggerUiConfig, swaggerUiOAuthProperties, swaggerUiConfigParameters, swaggerWelcomeCommon, objectMapperProvider);
    }

    @Override
    public Resource transform(HttpServletRequest request, Resource resource, ResourceTransformerChain transformerChain) throws IOException {
        this.swaggerUiConfigParameters.setConfigUrl(null); // force parent class to compute data
        return super.transform(request, resource, transformerChain);
    }
}

```

All you have to do is instanciate it from your `@Configuration` as the spring doc one is `ConditionnalOnMissingBean`

This is quite dirty yet, we see that the config url which is an attribute of a `Singleton` bean is computed for the first request. Hence we are populating application scope data with request scope data.... :cry:

**Comment by bnasslahsen** [comment]
should be fixed by #1748

**Comment by abenjell** [comment]
Hello @bnasslahsen,
This issue was not fixed by https://github.com/springdoc/springdoc-openapi/issues/1748
I reproduce the same issue even if i update springdoc-openapi to 1.6.11

**Comment by abenjell** [comment]
Thank you @antechrestos for your feedback.
but I'm still facing the same issue with  springdoc-openapi version =  1.6.11

**Comment by licenziato** [comment]
The problem is still present even in the springdoc-openapi version = 2.2.0. The only working solution for me is the one proposed by @antechrestos with a `SwaggerIndexPageTransformer ` bean. Any updates on this. It should be reopen disabling the cache cannot be the right solution.

**Comment by kerner1000** [comment]
The workaround by @antechrestos does not work for me, problem is still present. `springdoc-openapi-starter-webmvc-ui` version 2.2.0.

**Comment by robindijkhof** [comment]
@bnasslahsen can this be reopened?

**Comment by bnasslahsen** [comment]
@robindijkhof,

This can be reopened if an issue is confirmed.
You can share a minimal reproducible example , or a failing test in the springdoc project that highlights the issue and will be happy to reopen it.

**Comment by yqx1110** [comment]
I can confirm this issue still exists with springdoc 2.3.0, when accessing /xxx/swagger-ui/index.html, it uses the cached configUrl, however when accessing /xxx/swagger-ui.html the cached url will be updated and it works, but it redirects to /xxx/swagger-ui/index.html so people will bookmark this address and it will use cached url.
