### ISSUE TITLE
context-path is not respected when using Swagger UI (springdoc-openapi-ui 1.1.0)

### ISSUE THREAD

**Issue by davidmelia** [springdoc/springdoc-openapi#2]
Hi,

if you run your demo 'springdoc-openapi-test-app2' but change context-path to /myapp then swagger will not use this path i.e. it will call http://localhost:8080/pet instead of http://localhost:8080/myapp/pet

Thanks

**Comment by springdoc** [comment]
Fix is available on: springdoc-openapi-ui 1.1.1

**Comment by davidmelia** [comment]
Hi @springdoc, I'm just testing this issue using your demo (ui version 1.1.7)
springdoc-openapi-test-app2  by changing
```
server:
  servlet:
    context-path: /dave
```
and I still get the error detailed above where 

http://localhost:8080/dave/webjars/swagger-ui/index.html?

calls 

http://localhost:8080/user/

i.e no context root.  Any ideas?

springdoc-openapi-test-app1 does not work either.

**Comment by swim2sun** [comment]
@springdoc I got the same issue. In swagger UI, it alway accesses `/v3/api-docs` without a context path. The version is `1.1.30`

**Comment by springdoc** [comment]
Hi, 
 
 You can have a look at the demos: https://github.com/springdoc/springdoc-openapi-demos.git
 They contain examples how to set the context-path.

**Comment by swim2sun** [comment]
Hi, @springdoc , thanks for your reply. 

I have fix the issue by updating the version to `1.1.31`. 

My configuration in `application.yaml`:
```
server:
  servlet:
    context-path: /foo
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
```
