### ISSUE TITLE
Ui with multiple file @RequestPart only shows last part

### ISSUE THREAD

**Issue by hetzge** [springdoc/springdoc-openapi#55]
Given the following endpoint:
```
    @PostMapping(value = "/upload2", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public String upload2(@RequestPart("one") MultipartFile one, @RequestPart("two") MultipartFile two) {
        System.out.println(one.getName());
        System.out.println(two.getName());
        return "Ok";
    }
```
Then i can only see the upload input field for the last parameter ("two") in the ui.

I am using springdoc 1.1.24.

**Comment by sungtaek** [comment]
Right, I have a same issue.
Please support the multiple @RequestPart.

**Comment by springdoc** [comment]
Hi, 

 A fix for this issue will be available on v1.1.27 of springdoc-openapi. 
 You are invited to add feedback, to confirm if the issue is resolved.

**Comment by sungtaek** [comment]
Thanks for your quick fixes and answers.

But I still have a problem...
I use @RequestPart with MultipartFile and custom Object.
On the modified code, it seems to be merge only MultipartFile parameters.

Below is my code,
```
@PostMapping(value = "/test", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public Response createTest(@RequestPart("test") MyTest test, @RequestPart("image") MultipartFile imageFile) {
   ...
}
```
I want to receive test object as application/json and image file in multipart form request.
(in some cases, general type such as String and Integer may be used)
Is it possible to support?

Many thanks.

**Comment by petrleocompel** [comment]
This problem still exists. Any progress?

**Comment by Tordek947** [comment]
Hi, @springdoc. This issue should not be closed. I can confirm, that I have exactly the same issue as @sungtaek have described above. It persists even for v1.1.49. Is it going to be fixed? If you need help, I would be happy to contribute to fix this issue.

**Comment by Tordek947** [comment]
To be more precise, if among all \@RequestPart parameters, the first one is of type MultipartFile and the second one is some described data (to be converted to json), then both parameters at least appear in the docs (however, there are no schema showed in request section for json request part:
![image](https://user-images.githubusercontent.com/41228916/67413062-2507a380-f5c9-11e9-9cb4-5f15d3f9b34d.png)
**But** when the first \@RequestPart is not MultipartFile, then the issue persists (the only one \@requestPart parameter appeared is binary file:
![image](https://user-images.githubusercontent.com/41228916/67413325-98a9b080-f5c9-11e9-8817-8e408c74f104.png)

**Comment by springdoc** [comment]
Hi @Tordek947, 

 Can you please, the sample Java code to reproduce your issue?
 And the actual and the expected result, using the OpenAPI description (json or yaml format).

 You can also, propose a pull request, if you have an idea of the fix.

**Comment by Tordek947** [comment]
Hi, @springdoc 
Here is my code example:
`
@Tag(name = "project", description = "user projects API")
@RestController
@RequestMapping("/rest/users/{username}/projects")
public class ProjectController {

    @Autowired
    private ProjectService projectService;
    @Autowired
    private ProjectConverter projectConverter;

    @ApiResponse(responseCode = "201", description = "Successful operation")
    @PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @ResponseStatus(HttpStatus.CREATED)
    public ProjectData createUserProject(@PathVariable String username, @RequestPart CreateProjectData project,
            @RequestPart MultipartFile image) {
        return projectConverter.modelToData(projectService.createUserProject(username, project, image));
    }
...
`
As you can see here, the order of \@RequestParts is {json_data, multipartfile_data}. Having this the following oas snippet is being generated:
![image](https://user-images.githubusercontent.com/41228916/67624815-85ebe180-f83e-11e9-95c8-12808d604ec0.png)

**However**, if I swap arguments in the method:
`
public ProjectData createUserProject(@PathVariable String username, @RequestPart MultipartFile image,
            @RequestPart CreateProjectData project) {
        return projectConverter.modelToData(projectService.createUserProject(username, project, image));
    }
`, then I have oas generated correctly:
![image](https://user-images.githubusercontent.com/41228916/67624924-efb8bb00-f83f-11e9-9d24-e8fda5a53b9f.png)

Thus I assume, that the problem appears only when there are MultipartFile on the last place (previous \@RequestPart is silently ignored), otherwise all the OAS generation stuff works correctly.


Secondly, I found no way to send such a request using "Try it out" from swagger-ui page. During my investigation I found, that swagger-ui frondend don't specify Content-Type for the request part, which contains my json data (project) and thus spring refuse to process the request. But also I tried to make such a request using UI from Swagger Hub (and even specify 'contentType' in 'encoding' section for project as 'application\json'), but it doesn't append correct ContentType for the request either, so I suppose, this (second) issue is not the fault of this project.

**Comment by Tordek947** [comment]
Also I will try to provide a fix for the first issue during the next week. However, if you are going to fix it earlier, please, notify me here about it.

Thank you!

**Comment by springdoc** [comment]
Hi Guys, 

 Thank you for your help.
 The fix for this issue will be available on v1.2.0 of springdoc-openapi.
 Please leave your feedback, to confirm the issue is resolved.

**Comment by licenziato** [comment]
I can still see part of the issue: there are no schema shown in the request section for Json request part as reported also by @hpopov. Am'I missing something? 

Version currently used: springdoc 2.3.0.

Code to reproduce:
```java 
    @ApiResponse(responseCode = "201", description = "Successful operation")
    @io.swagger.v3.oas.annotations.parameters.RequestBody(content = @Content(encoding = @Encoding(name = "parameters", contentType = MediaType.APPLICATION_JSON_VALUE)))
    @PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.CREATED)
    public ConfigurationParameters echoTest(@RequestPart("file") MultipartFile file,
            @RequestPart("parameters") ConfigurationParameters parameters) {
        log.info("File: {}", file);
        log.info("Parameters: {}", parameters);
        return parameters;
    }
```

Result:

![image](https://github.com/springdoc/springdoc-openapi/assets/15328285/1e4f9017-213c-4669-b121-6b55b9e61ea3)

As you can see, the `parameters` part does not show the `ConfigurationParameters` template as shown in the response.
