### ISSUE TITLE
issues with spring data rest and @ManyToOne relationships

### ISSUE THREAD

**Issue by david-schneider-mpf** [springdoc/springdoc-openapi#792]
**Describe the bug**
for relationships like /property/{id}/childProperty, spring doc does not correctly describe the url, http methods or json

**To Reproduce**
see:

https://github.com/david-schneider-mpf/springdoc-data-rest

the README lists the major issues

**Expected behavior**
for such a relationship, the url should already have the child property name filled in
only the http methods supported by spring data rest should be displayed
links should be named correctly

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
@david-schneider-mpf, 

 Thank you for your feedback and your analysis.
 The main points are now addressed. You can test with the latest SNAPSHOT.

 For the links naming, it comes from the structure fo org.springframework.hateoas.Link. The generated structure looks more verbose.. But generated representation of the schema is correct.

**Comment by marcel-steinbach-mpf** [comment]
@bnasslahsen, thanks for the update. 

There's still an issue with the property naming, where it references are listed not with the correct name. SpringDoc lists it with the type name, instead of the reference name.
